-- Users Table
CREATE TABLE users (
    uid VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255),
    PRIMARY KEY (uid)
);

-- Room Table
CREATE TABLE room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id)
);

-- Reservation Table
CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id VARCHAR(255),
    room_id BIGINT,
    start_at TIMESTAMP(6),
    end_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- Foreign Keys
ALTER TABLE IF EXISTS reservation
    ADD CONSTRAINT FK_reservation_room
    FOREIGN KEY (room_id)
    REFERENCES room;

ALTER TABLE IF EXISTS reservation
    ADD CONSTRAINT FK_reservation_users
    FOREIGN KEY (user_id)
    REFERENCES users;